# Macro file for example B1
# To be run preferably in batch, without graphics:
# % exampleB1 run2.mac
#/run/numberOfWorkers 4
/run/initialize
/control/verbose 0
/run/verbose 0
#/tracking/verbose 0

/control/alias x_start_m -825.e-6
/control/alias x_end_m    825.e-6
# 22 steps is appropriate for 75 um in 1.65 mm
/control/alias x_step_m 75.e-6

# critial energy:
/gun/energy 4.458 keV
/control/loop LER-1-bunch.mac x_m {x_start_m} {x_end_m} {x_step_m}

